include:
- ./func/*
kind: ArchiveUploadSpec
name: func-tZUt

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-snapshot-fn-28dccd1a-2579-4dfe-8172-b69b9311952b
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-snapshot-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-tZUt
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-15T23:13:11Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  name: get-user-snapshot-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 6
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 70
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-snapshot-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_user_snapshot
    packageref:
      name: get-user-snapshot-fn-28dccd1a-2579-4dfe-8172-b69b9311952b
      namespace: default
  requestsPerPod: 1
  resources: {}
