include:
- ./func/*
kind: ArchiveUploadSpec
name: func-eLF9

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-snapshot-fn-fd5571eb-cdb1-42a8-96b0-3154b7cc0b5d
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-snapshot-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-eLF9
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-12T18:14:23Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-snapshot-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-snapshot-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_user_snapshot
    packageref:
      name: get-user-snapshot-fn-fd5571eb-cdb1-42a8-96b0-3154b7cc0b5d
      namespace: default
  requestsPerPod: 1
  resources: {}
