apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-user-snapshot-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-user-snapshot-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get_user_snapshot
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get_user_snapshot
