include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-7MuV

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sup-tckt-snapshot-fn-4fea8d16-c35b-4ad4-bf44-d0a34ff8f13a
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-7MuV
  environment:
    name: sup-tckt-snapshot-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T19:20:11Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: sup-tckt-snapshot-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: sup-tckt-snapshot-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: sup-tckt-snapshot-fn-4fea8d16-c35b-4ad4-bf44-d0a34ff8f13a
      namespace: default
  requestsPerPod: 10000
  resources: {}
