include:
- ./func/*
kind: ArchiveUploadSpec
name: func-eZH6

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-snapshot-fn-d612fe9d-4d56-4d70-b714-0c2778b55600
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-snapshot-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-eZH6
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-15T19:43:22Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-snapshot-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-snapshot-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_user_snapshot
    packageref:
      name: get-user-snapshot-fn-d612fe9d-4d56-4d70-b714-0c2778b55600
      namespace: default
  requestsPerPod: 1
  resources: {}
