include:
- ./func/*
kind: ArchiveUploadSpec
name: func-NuB6

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: post-user-ticket-fn-52dca5fc-6266-4486-a3ca-8d73bff3ead6
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: post-user-ticket-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-NuB6
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-06-03T11:29:57Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: post-user-ticket-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: post-user-ticket-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.post_user_ticket
    packageref:
      name: post-user-ticket-fn-52dca5fc-6266-4486-a3ca-8d73bff3ead6
      namespace: default
  requestsPerPod: 1
  resources: {}
