apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 6d0b9fc8-b5d5-4494-b696-3be8ba8a9060
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: post-user-ticket-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /post_user_ticket
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /post_user_ticket
